### ISSUE TITLE
Underscore in outputs

### ISSUE THREAD

**Issue by coyotree** [ivanlfm/BGB_BSM_multiple_trees#1]
Hello,
[Average_state_by_state_all_transitions_BSM.txt](https://github.com/ivanlfm/BGB_BSM_multiple_trees/files/6735293/Average_state_by_state_all_transitions_BSM.txt)

Been playing around with this script and I successfully got it to run, but I noticed that the tip coding does not match how the tips are actually coded in the output. For example, I'll have coded a tip as occurring in F but the figures label it as C. Then I took a look at the outputs and they were very odd, especially the LTT plot. The first column of the output tables has an underscore in the table as if it is a state. When looking at 'tipranges', etc. there is not an underscore. However, it does show up when the 'statenames' and 'statelabels' objects are made. See below. Attaching an output for your perusal.

`> getareas_from_tipranges_object(tipranges)
[1] "A" "P" "H" "S" "C" "F" "M"

> head(statenames)
[[1]]
[1] "_"

[[2]]
[1] "A"

[[3]]
[1] "P"

[[4]]
[1] "H"

[[5]]
[1] "S"

[[6]]
[1] "C"
`

Curious if you know where this underscore might be coming from. The geography file set up the same way when use BioGeoBEARS (I think! I can't seem to find any issue) and I have never had this issue. Thanks for any advice! This is a great resource!

Best,
Cody Coyotee

**Comment by ivanlfm** [comment]
Hi Cody, the underscore ("_") in the output table is the "null" range that
BioGeoBEARS includes by default, unless you use
*BioGeoBEARS_run_object$include_null_range
= FALSE*.
Thus, the output tables (as the one you attached) should include a state
"_".

>  I'll have coded a tip as occurring in F but the figures label it as C
This is weird - in my test datasets the figures correspond to the correct
areas, so I am not sure what is going on with your dataset. Does it happen
just with the LTT plot? Perhaps the code I wrote to get the state names for
the LTT plot is not general enough, I would love to take a look at your
outputs and figure out what is going on, you can send them to me privately
if you prefer. Thanks for letting me know!
Best, Ivan

Em ter., 29 de jun. de 2021 às 14:33, Cody Howard ***@***.***>
escreveu:

**Comment by ivanlfm** [comment]
Hi Cody, sorry for the slow response on this.

I checked your inputs -- you had BioGeoBEARS_run_object$include_null_range = FALSE, meaning that you were using the DEC* model that does not include a null range. This is why you were getting the figures with some taxa with the wrong area. I think the script will not support the DEC* model for now, so please run your analysis with BioGeoBEARS_run_object$include_null_range = TRUE. Sorry!

Regarding the LTT plot -- the script had a bug that prevented the LTT plots to be output correctly if time_period_size was different from 1 (it was set to 4 in your input)
[Clade2.BioGeoBEARS_posterior_trees_count_events_v33.txt](https://github.com/ivanlfm/BGB_BSM_multiple_trees/files/7026538/Clade2.BioGeoBEARS_posterior_trees_count_events_v33.txt)
. Take a look at this correct version which should work. Thanks for pointing this to me!

Best,
Ivan
