### ISSUE TITLE
Error when running BGB with dispersal multipliers matrix

### ISSUE THREAD

**Issue by pelow22** [ivanlfm/BGB_BSM_multiple_trees#2]
Hello Ivan,

I ran your tutorial data on spiders and they worked fine (time stratified and areas allowed).
Then, I ran my data under the unconstrained model (DEC) and they worked fine.

However, when I added a dispersal multiplier matrix to the model (DEC), I got this error:
![image](https://user-images.githubusercontent.com/65909510/128917780-70a60a38-0257-403e-afa7-3727da3a5e30.png)
![image](https://user-images.githubusercontent.com/65909510/128918075-da7c7564-4c6a-4692-9a26-246a15433ba0.png)
![image](https://user-images.githubusercontent.com/65909510/128917678-fd36d647-f926-452d-9254-bd2c6cb3b8ac.png)
Could you help me on this issue?

Excellent coding, by the way.
Thank you in advance,

Peter

**Comment by ivanlfm** [comment]
Hello Peter, thanks for letting me know. 
Can you please send me the input files so I can replicate the issue and try to find a solution?
Thanks!
Ivan

**Comment by pelow22** [comment]
Hello Ivan,
sure.
Peter

**Comment by ivanlfm** [comment]
Hi Peter, there was a small bug that prevented the dispersal matrices to be read correctly if time_stratified was set to FALSE.
Here is a fixed version that should run, I will later correct it in the main files. Thanks a lot for letting me know! 
Best,
Ivan
[BioGeoBEARS_posterior_trees_count_events_v34.txt](https://github.com/ivanlfm/BGB_BSM_multiple_trees/files/7026428/BioGeoBEARS_posterior_trees_count_events_v34.txt)

**Comment by pelow22** [comment]
Thank you.
Best regards,
Peter
