### ISSUE TITLE
Error in NON-stratified analysis

### ISSUE THREAD

**Issue by luishdez35** [ivanlfm/BGB_BSM_multiple_trees#5]
Hi Ivan, greetings from Mexico. I'm trying to use your script, but I'm encountering the following error: 

```
"Error in if (is.na(states_list[[i]])) { : the condition has length > 1. 
In addition: Warning message: In (function (npt = min(n + 2L, 2L * n), rhobeg = NA, rhoend = NA, : 
unused control arguments ignored." 
```

I've already updated packages, made sure everything was installed, checked my input files, and I'm still facing the same error. It's not producing any results for me; it only gives me the results from BioGeoBears. Could you help me out with this issue?

Best.

**Comment by ivanlfm** [comment]
Hi Luis, thanks for your message. Can you please send me your input files so I can try and reproduce the error? Thanks.

**Comment by luishdez35** [comment]
Sure I can send you the input files. You can download the files here: 
[https://drive.google.com/drive/folders/1R6HIXky2B3QCYNH8dpUXk7_K9CySWxAN?usp=share_link](url)

Gracias Ivan

**Comment by ivanlfm** [comment]
Hi Luis, I also need the script that generated the error. Thanks!

**Comment by luishdez35** [comment]
Hi Ivan, 
I forgot the script sorry. 
I am going to upload the file to the google drive folder right now. 

Thanks

**Comment by ivanlfm** [comment]
Thanks. I was trying from scratch, and I get the error you mention in this line (654):

> get_inputs_for_stochastic_mapping(res=BGB_res)

Your computer has 4 cores.

Your computer has 4 cores. You have chosen to use:
num_cores_to_use = 2 cores for the matrix exponentiations in the likelihood calculations.
Started cluster with 2 cores.

Currently, cluster_already_open=socket cluster with 2 nodes on host ‘localhost’

Detected NON-stratified input. Running get_inputs_for_stochastic_mapping_from_results_object().
Read 7 items
Read 100 items
**Error in if (is.na(states_list[[i]])) { : the condition has length > 1**

The get_inputs_for_stochastic_mapping belongs to BioGeoBEARS. I know some people (including me!) had trouble with BSM some time ago, see this thread: https://groups.google.com/g/biogeobears/c/NPnR8Z0CK40

May you please check with Nick if it is an issue with this function? Perhaps you should try to run BSM with your data outside my script, just to check that the issue may be.

**Comment by ivanlfm** [comment]
Also: when I set 

dispersal_matrix = FALSE
area_adjacency = FALSE
distance_matrix = FALSE
areas_allowed = FALSE
(lines 121-131)

the script runs smoothly. I suspect the problem might be with the interaction between the get_inputs_for_stochastic_mapping function and one of your input files, or some of these options. Please check this carefully. 

Also, by checking them, some of them are not necessary -- if areas_allowed and manual_dispersal_multipliers are all 1, you don't need to use them, as 1 is the default value of BioGeoBEARS.

(Finally, correct nodes_of_interest <- list( c ( ) ) to nodes_of_interest <- list( ), otherwise you will get another error)

**Comment by ivanlfm** [comment]
I suspect the area_adjacency option might be the culprit. Please keep me posted if you find a solution.

**Comment by luishdez35** [comment]
Thank you Ivan, I am going to check that and I let you now what happen. 

Thanks

**Comment by luishdez35** [comment]
Hola Ivan.
I have an update.
I tried again with FALSE in lines 121-131 and work fine, but with this error:

```
Error in win.metafile(file = paste(dir_name, "/Average_LTT_by_area.emf",  : 
  could not find function "win.metafile"
In addition: There were 42 warnings (use warnings() to see them)
```

and I search the error and its because I use MacOS and I tried in a Windows machine, and error was gone, and the script give me all the outputs, I need to review my inputs files, but in BioGeoBears run smoothly. I am going to try to run the BSM in BioGeoBears and let you now. 

**Also in Windows give this warnings messages:**
```
Warning messages:
1: In (function (npt = min(n + 2L, 2L * n), rhobeg = NA,  ... :
  unused control arguments ignored
2: In (function (npt = min(n + 2L, 2L * n), rhobeg = NA,  ... :
  unused control arguments ignored
3: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 8 (<-LuisC-Hdez:11616)
4: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 7 (<-LuisC-Hdez:11616)
5: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 6 (<-LuisC-Hdez:11616)
6: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 5 (<-LuisC-Hdez:11616)
7: In (function (npt = min(n + 2L, 2L * n), rhobeg = NA,  ... :
  unused control arguments ignored
8: In for (i in seq_len(n)) { ... : closing unused connection 12 (<-LuisC-Hdez:11616)
9: In for (i in seq_len(n)) { ... : closing unused connection 11 (<-LuisC-Hdez:11616)
10: In for (i in seq_len(n)) { ... :
  closing unused connection 10 (<-LuisC-Hdez:11616)
11: In for (i in seq_len(n)) { ... : closing unused connection 9 (<-LuisC-Hdez:11616)
12: In (function (npt = min(n + 2L, 2L * n), rhobeg = NA,  ... :
  unused control arguments ignored
13: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 8 (<-LuisC-Hdez:11616)
14: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 7 (<-LuisC-Hdez:11616)
15: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 6 (<-LuisC-Hdez:11616)
16: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 5 (<-LuisC-Hdez:11616)
17: In (function (npt = min(n + 2L, 2L * n), rhobeg = NA,  ... :
  unused control arguments ignored
18: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 12 (<-LuisC-Hdez:11616)
19: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 11 (<-LuisC-Hdez:11616)
20: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 10 (<-LuisC-Hdez:11616)
21: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 9 (<-LuisC-Hdez:11616)
22: In (function (npt = min(n + 2L, 2L * n), rhobeg = NA,  ... :
  unused control arguments ignored
23: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 8 (<-LuisC-Hdez:11616)
24: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 7 (<-LuisC-Hdez:11616)
25: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 6 (<-LuisC-Hdez:11616)
26: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 5 (<-LuisC-Hdez:11616)
27: In (function (npt = min(n + 2L, 2L * n), rhobeg = NA,  ... :
  unused control arguments ignored
28: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 12 (<-LuisC-Hdez:11616)
29: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 11 (<-LuisC-Hdez:11616)
30: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 10 (<-LuisC-Hdez:11616)
31: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 9 (<-LuisC-Hdez:11616)
32: In (function (npt = min(n + 2L, 2L * n), rhobeg = NA,  ... :
  unused control arguments ignored
33: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 8 (<-LuisC-Hdez:11616)
34: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 7 (<-LuisC-Hdez:11616)
35: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 6 (<-LuisC-Hdez:11616)
36: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 5 (<-LuisC-Hdez:11616)
37: In (function (npt = min(n + 2L, 2L * n), rhobeg = NA,  ... :
  unused control arguments ignored
38: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 12 (<-LuisC-Hdez:11616)
39: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 11 (<-LuisC-Hdez:11616)
40: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 10 (<-LuisC-Hdez:11616)
41: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 9 (<-LuisC-Hdez:11616)
42: In (function (npt = min(n + 2L, 2L * n), rhobeg = NA,  ... :
  unused control arguments ignored

```

Best an thank you

**Comment by ivanlfm** [comment]
Hi Luis, sorry about the win.metafile function -- you may replace it with other function for outputting graphics, such as pdf:
pdf(file=paste(dir_name, "/Average_LTT_by_area.pdf", sep =""))
That should get it running on Mac.
I am unsure about the warning messages, they might come from BioGeoBEARS.

Please keep me posted about the issue with area_adjacency.
